// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ExpenseHistory(props) {
  return React.createElement("div", {
              className: "box"
            });
}

var make = ExpenseHistory;

export {
  make ,
}
/* react Not a pure module */
