// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HeaderCmp from "./components/header/HeaderCmp.bs.js";
import * as ExpenseHistory from "./components/expenseHistory/ExpenseHistory.bs.js";

function App(props) {
  return React.createElement("div", {
              className: "app__container"
            }, React.createElement(HeaderCmp.make, {}), React.createElement(ExpenseHistory.make, {}));
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
